[package]
name = "pedantic"
version = "0.1.0"
authors = ["Marius Meschter <git@meschter.me>"]
edition = "2024"
description = "Provide a checked newtype wrapper"
readme = "README.md"
repository = "https://github.com/onestay/pedantic"
license = "MIT OR Apache-2.0"
keywords = ["newtype", "checked", "strict", "typing", "parse", "refine"]
categories = ["rust-patterns", "data-structures"]

[features]
regex = ["dep:regex"]
serde = ["dep:serde"]

[dependencies]
paste = "1.0.15"
regex = { version = "1", optional = true }
serde = { version = "1", optional = true }

[dev-dependencies]
rstest = "0.26.1"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
